# Generated by Django 5.1.4 on 2024-12-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_encryptionkey_remove_uploadedfile_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='iv',
            field=models.BinaryField(default=''),
            preserve_default=False,
        ),
    ]
